name: Validate
description: Lints, builds, and tests the project whenever a pull request is opened or merged

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  lint:
    needs: [build] # Build output is required for linting
  
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm clean-install

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm clean-install

      - name: Build
        run: npm run build

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
